name: "Backport to Stable"
on:
  workflow_run:
    workflows: [Update flakes & npins]
    types: 
    - requested
  workflow_dispatch:
jobs:
  backport:
    name: Backport
    runs-on: ubuntu-slim
    steps:
    # Creates token to allow for workflow event calls
    - uses: actions/create-github-app-token@v3
      id: generate-token
      with:
        app-id: ${{ secrets.HEADPATS }}
        private-key: ${{ secrets.LAP_PILLOW }}

    # Persisting is okay as create PR automatically handles that
    - uses: actions/checkout@v6
      with:
        ref: stable

    - name: Check if the Saturday is an even number
      id: saturday
      run: |
        WEEK=$(date -u +%V)
        if [ $((WEEK % 2)) -ne 0 ]; then 
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    # Makes stable the new master branch
    - name: Reset stable branch
      if: steps.saturday.outputs.skip == 'false'
      run: |
        git fetch origin master:master
        git reset --hard master

    # Creates pull request
    # No need to sign commits as Nahida doesn't commit anything, all commits are already signed before
    - name: Create Pull Request
      if: steps.saturday.outputs.skip == 'false'
      id: pr
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ steps.generate-token.outputs.token }}
        branch: master-to-stable
        title: "[Backport] Merge master to stable"
        body: "This Pull Request is automatically generated and merges changes from master to stable"
        labels: |
          automated pr
        draft: false
