name: "Push derivations to cachix"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'flake.lock'
      - 'pkgs/**'
  pull_request:

jobs:
  build-derivations:
    name: Build derivations & Push to Cachix
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Filter
      uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          lockfile:
            - 'flake.lock'
          packages:
            - 'pkgs/**'

    - name: Aggressive disk space removal
      if: steps.filter.outputs.lockfile == 'true'
      uses: wimpysworld/nothing-but-nix@v10
      with:
        nix-permission-edict: true  

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_version: 2.31.2
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Cachix
      uses: cachix/cachix-action@v16
      with:
        name: sumee
        authToken: '${{ secrets.CACHIX_AUTH }}'

    - name: Push flake inputs
      if: steps.filter.outputs.lockfile == 'true'
      run: nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)'

    - name: Build system derivations
      if: steps.filter.outputs.lockfile == 'true'
      run: nix run github:Mic92/nix-fast-build -- --no-nom --skip-cached  --flake ".#checks.$(nix eval --raw --impure --file builtins.currentSystem)"

    - name: Build package derivations
      if: steps.filter.outputs.packages == 'true'
      run: nix build .#nahidacursor .#papiteal .#vesktop
