name: "Push derivations to cachix"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'flake.lock'
      - 'npins/sources.json'
      - 'pkgs/**'

  # Run when pull request is labeled (if conditions later restrict it to run only if PR is made by nahida)
  pull_request_target:
    types: [labeled]

jobs:
  archives:
    name: Push archives to cachix
    if: (github.event_name == 'push') || (github.event_name == 'pull_request' && github.actor == 'nahida-greenery[bot]')
    runs-on: ubuntu-latest
    outputs:
      lockfile: ${{ steps.filter.outputs.lockfile }}
      packages: ${{ steps.filter.outputs.packages }}
    steps:
    - uses: actions/checkout@v6
    - uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          lockfile: 'flake.lock'
          npins: 'npins/sources.json'
          packages: 'pkgs/**'

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_version: 2.31.2

    - name: Cachix
      uses: cachix/cachix-action@v17
      with:
        name: sumee
        authToken: '${{ secrets.CACHIX_AUTH }}'

    # Pushes flakes based on cachix CI guide
    - name: Push flake inputs to cachix
      if: steps.filter.outputs.lockfile == 'true' || github.event.review.state == 'approved'
      run: nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)'

    # Cursed way of one-line command to print out npins path for cachix
    - name: Push npins archive to cachix
      if: steps.filter.outputs.npins == 'true' || github.event.review.state == 'approved'
      run: |
        for i in $(nix run --quiet nixpkgs#npins -- show | sed -n "/: (git repository)/s/: (git repository)//p"); do echo -e "$(nix run --quiet nixpkgs#npins -- get-path "$i")"; done

  derivations:
    needs: archives
    name: Push derivations to cachix
    if: ${{ needs.archives.outputs.lockfile == 'true' || needs.archives.outputs.packages == 'true' || (github.event_name == 'pull_request' && github.actor == 'nahida-greenery[bot]') }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6

    - name: Aggressive disk space removal
      if: ${{ needs.archives.outputs.lockfile == 'true' || (github.event_name == 'pull_request' && github.actor == 'nahida-greenery[bot]') }}
      uses: wimpysworld/nothing-but-nix@v10
      with:
        nix-permission-edict: true # Ensure install nix action has the right permissions

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_version: 2.31.2

    - name: Cachix
      uses: cachix/cachix-action@v17
      with:
        name: sumee
        authToken: '${{ secrets.CACHIX_AUTH }}'


    # Evaluates & Builds only for the system based on the matrix (x64 for ubuntu-latest, arm64 for ubuntu-arm)
    - name: Build system derivations
      if: ${{ needs.archives.outputs.lockfile == 'true' || (github.event_name == 'pull_request' && github.actor == 'nahida-greenery[bot]') }}
      run: nix run --quiet github:Mic92/nix-fast-build -- --no-nom --skip-cached  --flake ".#checks.$(nix eval --raw --impure --expr builtins.currentSystem)"

    # More of an edge case honestly since nix-fast-build builds packages too
    - name: Build package derivations
      if: ${{ needs.archives.outputs.packages == 'true' }}
      run: nix build --quiet .#nahidacursor .#papiteal .#dickord .#caddyscale
