name: "Sync branches"
on:
  workflow_dispatch:
  push:
    branches:
    - stable # Runs when merged to stable (only happens when github-actions merges nahida PR)
jobs:
  sync:
    name: Sync stable & master after PR merged
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
    - uses: actions/create-github-app-token@v3
      id: generate-token
      with:
        client-id: ${{ secrets.HEADPATS }}
        private-key: ${{ secrets.LAP_PILLOW }}

    # Checkout stable branch
    - uses: actions/checkout@v6
      with:
        ref: stable
        token: ${{ steps.generate-token.outputs.token }}
        persist-credentials: false

    # Merge branches without committing & ensure it doesn't fast-forward
    - name: Merge stable to master
      run: |
        git fetch origin
        git checkout master
        git merge stable --no-commit --no-ff

    # Signed commit
    - name: Commit & Push changes
      uses: iarekylew00t/verified-bot-commit@v2
      with:
        allow-empty-commit: true
        message: 'Chore: Sync Branches'
        token: ${{ steps.generate-token.outputs.token }}
        files: |
          **
