name: Sync Tailscale ACLs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  acls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with: 
          fetch depth: 2

      - shell: pwsh
        id: check_file_changed
        run:
          $diff = git diff --name-only HEAD^ HEAD

          $SourceDiff = $diff | Where-Object { $_ -match 'policy.hujson' }
          $HasDiff = $SourceDiff.Length -gt 0

          Write-Host "::set-output name=acl_changed::$HasDiff"


      - name: Deploy ACL
        if: steps.check_file_changed.outputs.acl_changed == 'True' && github.event_name == 'push'
        id: deploy-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: apply

      - name: Test ACL
        if: steps.check_file_changed.outputs.acl_changed == 'True' && github.event_name == 'pull_request'
        id: test-acl
        uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ secrets.TS_API_KEY }}
          tailnet: ${{ secrets.TS_TAILNET }}
          action: test

