name: "Update flakes & npins"
on:
  schedule:
    - cron: "0 9 * * 6" # 9 am UTC on Saturday
  workflow_dispatch:
jobs:
  update:
    name: Update script
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
    - uses: actions/create-github-app-token@v2
      id: generate-token
      with:
        app-id: ${{ secrets.HEADPATS }}
        private-key: ${{ secrets.LAP_PILLOW }}
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_version: 2.31.2
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Update flakes
      run: nix flake update

    - name: Update npins
      run: nix shell nixpkgs#npins --command npins update

    - name: Push Changes
      run: |
          git config --local user.email "nahida-greenery[bot]@users.noreply.github.com"
          git config --local user.name "nahida-greenery[bot]"
          ggit diff --staged --quiet || git commit -am "Chore: Update flakes & npins"
          git push "https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
