name: "Update Blocklist"
on:
  schedule:
    - cron: "0 9 * * *" # 9 am UTC
  workflow_dispatch:
jobs:
  blocklist:
    name: Update Blocklist
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v6

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_version: 2.31.2
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Update
      run: nix shell nixpkgs#npins --command npins update blocklist

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
          sign-commits: true
          add-paths: npins/sources.json
          branch: blocklist-update
          delete-branch: true
          draft: false
          commit-message: "Update Blocklist"
          title: "[Chore] Update Blocklist"
          body: >
            Automated Pull Request to Update Blocklist at 9 am UTC.
          labels: automated pr

    - name: Auto-merge github-actions bot commit
      if: github.actor == 'github-actions[bot]'
      run: gh pr merge --merge --auto "1"

