name: "Update flakes & npins"
on:
  schedule:
    - cron: "0 9 * * 6" # 9 am UTC on Saturday
  workflow_dispatch:
jobs:
  update:
    name: Initialize Token
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/create-github-app-token@v2
      id: generate-token
      with:
        app-id: ${{ secrets.HEADPATS }}
        private-key: ${{ secrets.LAP_PILLOW }}
    - uses: actions/checkout@v6

    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v34
      with:
        nix_version: 2.31.2
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

    - name: Update Flakes
      run: nix flake update

    - name: Update npins
      run: nix shell nixpkgs#npins --command npins update

    - name: Push Changes
      run: |
          git config --local user.email "nahida-greenery[bot]@users.noreply.github.com"
          git config --local user.name "nahida-greenery[bot]"
          git add flake.lock npins/sources.json
          git diff --staged --quiet || git commit -m "Chore: Update flakes & npins"
          git push
